Revert "feat: zstd:chunked"
This reverts commit fb1a308aabe1464ef01bd3b52a0693476281ec52.

Let's see if this fixes
```
error: Upgrading composefs: Performing Upgrade Operation: Pulling composefs repository: Pulling image into composefs repository: Unable to pull container image docker://ghcr.io/renner0e/aurora-composefs: Failed to pull config Descriptor { media_type: ImageConfig, digest: Digest { algorithm: Sha256, value: "sha256:2cfb2e2dd19c719ad26e468ba67488eb42ff5a1db97afaae7fc10cd6570e4899", split: 6 }, size: 43904, urls: None, annotations: None, platform: None, artifact_type: None, data: None }: unexpected EOF reading tar entry
```